# Generated by Django 3.2.7 on 2021-09-21 18:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(),
        ),
    ]
