# Generated by Django 3.2.7 on 2021-09-21 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
